image: haskell:8.0.1

services:
  - postgres:9.4

variables:
  POSTGRES_DB: betty_test
  POSTGRES_USER: betty
  POSTGRES_PASSWORD: betty

cache:
  untracked: true
  paths:
    - $(pwd)/.stack/

before_script:
  - export STACK_ROOT=$(pwd)/.stack
  - apt-get update -qq && apt-get install -qq -y m4 libpq-dev
  - cp secrets.m4.example secrets.m4
  - make files
  - stack install hspec-discover
  - stack install --only-dependencies -j 4

test:
  script:
    - export PGHOST=postgres
    - export PGUSER=$POSTGRES_USER
    - export PGPASS=$POSTGRES_PASSWORD
    - export PGDATABASE=$POSTGRES_DB
    - stack test --coverage

after_script:
  - stack hpc report betty
