steps:
  - imports:
      align: file

  - language_pragmas:
      style: vertical
      remove_redundant: true

  - records: {}

  - trailing_whitespace: {}

columns: 78

language_extensions:
    - TemplateHaskell
    - QuasiQuotes
    - TypeFamilies
