# Use Travis CI's container infrastructure to enable caching.
sudo: false

# "haskell" will set up the whole haskell-platform.  We don't need that.
language: c

addons:
  apt:
    packages:
    - libgmp-dev
  postgresql: "9.1"

env:
  - ARGS=""
  - ARGS="--resolver lts-2"
  - ARGS="--resolver lts-3"
  - ARGS="--resolver lts"
  - ARGS="--resolver nightly"

before_install:
  - mkdir -p $HOME/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.5.0/stack-0.1.5.0-x86_64-linux.tar.gz | tar xz --strip-components=1 -C ~/.local/bin
  - echo $PATH
  - ls $HOME/.local/bin

install:
  - cp secrets.m4.example secrets.m4
  - make

before_script:
  - psql -c 'create database betty_test;' -U postgres

script:
  - stack $ARGS --no-terminal --install-ghc test

# Speed up subsequent builds using Stack caching.  
cache:
  directories:
    - $HOME/.stack
