#
# TODO: Use a newer Cabal version.  I would like to use Cabal-1.22 on
# travis-ci.org, but using that version of Cabal produces this error:
#
#     cabal: You need to re-run the 'configure' command. The version
#     of Cabal being used has changed (was Cabal-1.18.1.5, now
#     Cabal-1.22.2.0). Additionally the compiler is different (was
#     ghc-7.8, now ghc-7.10) which is probably the cause of the
#     problem.
#
# Cabal 1.20 seems to work OK, so I'll just use that for now.
#

env:
  - CABALVER=1.20 GHCVER=7.8.4 HAPPYVER=1.19.5 ALEXVER=3.1.4

addons:
  postgresql: "9.3"

before_install:
  - travis_retry sudo apt-add-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER happy-$HAPPYVER alex-$ALEXVER
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/happy/$HAPPYVER/bin:/opt/alex/$ALEXVER/bin:$PATH

install:
  - cabal --version
  - ghc --version
  - happy --version
  - alex --version
  - travis_retry cabal update
  - cp secrets.m4.example secrets.m4
  - make
  - cabal sandbox init
  - cabal install yesod-bin
  - export PATH=$(pwd)/.cabal-sandbox/bin:$PATH
  - cabal install --only-dependencies --enable-tests --reorder-goals --max-backjumps=-1 -j
  - cabal configure -fdev --enable-tests
  - cabal build
  - ls $(pwd)/.cabal-sandbox/bin

before_script:
  - psql -c 'create database betty_test;' -U postgres

script:
  - yesod test
