#
# TODO: Use a newer Cabal version.  I would like to use Cabal-1.22 on
# travis-ci.org, but using that version of Cabal produces this error:
#
#     cabal: You need to re-run the 'configure' command. The version
#     of Cabal being used has changed (was Cabal-1.18.1.5, now
#     Cabal-1.22.2.0). Additionally the compiler is different (was
#     ghc-7.8, now ghc-7.10) which is probably the cause of the
#     problem.
#
# Cabal 1.20 seems to work OK, so I'll just use that for now.
#

# Use Travis CI's container infrastructure to enable caching.
sudo: false

# "haskell" will set up the whole haskell-platform.  We don't need that.
language: c

addons:
  apt:
    packages:
    - libgmp-dev

env:
  # - CABALVER=1.20 GHCVER=7.8.4 HAPPYVER=1.19.5 ALEXVER=3.1.4
  - ARGS=""
  - ARGS="--resolver lts-2"
  - ARGS="--resolver lts-3"
  - ARGS="--resolver lts"
  - ARGS="--resolver nightly"

addons:
  postgresql: "9.1"

before_install:
  # - travis_retry sudo apt-add-repository -y ppa:hvr/ghc
  # - travis_retry sudo apt-get update
  # - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER happy-$HAPPYVER alex-$ALEXVER
  # - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/happy/$HAPPYVER/bin:/opt/alex/$ALEXVER/bin:$PATH
  - mkdir -p $HOME/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.5.0/stack-0.1.5.0-x86_64-linux.tar.gz | tar xz --strip-components=1 -C ~/.local/bin
  - echo $PATH
  - ls $HOME/.local/bin
  - dpkg -l | grep libgmp-dev
  - gcc -lgmp
  - stack $ARGS --no-terminal --install-ghc test --haddock

install:
  # - cabal --version
  - ghc --version
  - happy --version
  - alex --version
  - cp secrets.m4.example secrets.m4
  - make
  - cabal sandbox init
  - travis_retry cabal update  
  - travis_wait cabal install yesod-bin
  - export PATH=$(pwd)/.cabal-sandbox/bin:$PATH
  - cabal install --only-dependencies --enable-tests --reorder-goals --max-backjumps=-1 -j
  - ls $(pwd)/.cabal-sandbox/bin

before_script:
  - psql -c 'create database betty_test;' -U postgres

script:
  - yesod test

# Speed up subsequent builds using Stack caching.  
cache:
  directories:
    - $HOME/.stack
