--
-- Running Setup.hs (like "runhaskell Setup.hs build", or indirectly
-- by cabal) creates Betty/Version.hs, which has a function that
-- returns the abbreviated git commit hash.
--
-- The commit hash string is displayed at the footer of the site.
--
-- (Version.hs also used to return a time stamp of the build
-- previously, but this was only approximate at best, and turned out
-- to be rather complicated to make work with both ghc-7.10.x and
-- ghc-7.8.x.  Might revisit this later, but it is no big deal.  Might
-- as well not.)
--

import Prelude

import Control.Monad                   (liftM)
import System.Process                  (readProcess)

import Distribution.PackageDescription (HookedBuildInfo, emptyHookedBuildInfo)
import Distribution.Simple             (defaultMainWithHooks, preConf,
                                        simpleUserHooks)

import Data.Time.Clock                 (UTCTime (..), getCurrentTime)
import Data.Time.Format                (formatTime)

main :: IO ()
main = defaultMainWithHooks hooks
    where hooks = simpleUserHooks { preConf = bettyPreConf }

bettyPreConf :: t -> t1 -> IO HookedBuildInfo
bettyPreConf _ _ = do
    putStrLn "Generating Betty/Version.hs"

    desc <- liftM (filter (/= '\'') . filter (/= '\n')) $
            readProcess "git" ["show", "HEAD", "-s", "--format='%h'"] ""

    writeFile "Betty/Version.hs" $ unlines
        [ "module Betty.Version where"
        , ""
        , "-- Generated by Setup.hs.  Do not edit!"
        , ""
        , "import Data.String"
        , ""
        , "gitCommitHash :: String"
        , "gitCommitHash = " ++ show (init desc)
        ]

    return emptyHookedBuildInfo

