--
-- Running Setup.hs (like so: "runhaskell Setup.hs build") creates
-- Betty/Version.hs, which has functions to show version and time
-- stamp of the build.  These strings are displayed at the footer of
-- the site.
--
-- Surely enough, 'buildTime' timestamps are approximations at best.
--

import Control.Monad                   (liftM)
import Data.Time.Clock                 (UTCTime (..), getCurrentTime)
import Distribution.PackageDescription (HookedBuildInfo, emptyHookedBuildInfo)
import Distribution.Simple
import Prelude
import System.Process                  (readProcess)

import Data.Time.Format                (formatTime)
import System.Locale                   (defaultTimeLocale)

main :: IO ()
main = defaultMainWithHooks myHooks
    where myHooks = simpleUserHooks { preConf = bettyPreConf }

format :: UTCTime -> String
format = formatTime defaultTimeLocale "%F %T %Z"

bettyPreConf :: t -> t1 -> IO HookedBuildInfo
bettyPreConf _ _ = do
    putStrLn "Generating Betty/Version.hs"

    desc <- liftM (filter (/= '\'') . filter (/= '\n')) $
            readProcess "git" ["show", "HEAD", "-s", "--format='%h'"] ""
    now  <- fmap format getCurrentTime

    writeFile "Betty/Version.hs" $ unlines
        [ "module Betty.Version where"
        , ""
        , "-- Generated by Setup.hs.  Do not edit!"
        , ""
        , "import Data.String"
        , ""
        , "gitCommitHash :: String"
        , "gitCommitHash = " ++ show (init desc)
        , ""
        , "buildTime :: String"
        , "buildTime = " ++ show now
        ]
    return emptyHookedBuildInfo

